---
title: "PosterReport"
author: "Lukáš Hejtmánek"
date: "2 July 2016"
output: html_document
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/',
                      echo=FALSE, warning=FALSE, message=FALSE)
```

```{r,ïnclude = FALSE}
source("Scripts/LoadingScript.R")
```

```{r, echo = FALSE}
tabEyeQuests = fread("tabEyeQuests.csv",sep=";")
tabMRIQuests = fread("tabMRIQuests.csv", sep=";")
```

Plotting average time and idstance in Eyetracker learn vs trial
```{r}
tab = tabEyeQuests[!is.na(time) & !is.na(distance)]
completePatientQuests = tab[,list(hasBoth = ((.N)==2)),by = list(participant_id,id)]
completePatientQuests = completePatientQuests[hasBoth==TRUE]
tab = merge(tab, completePatientQuests, by=c("participant_id", "id"), all = F)
tabM = tabMRIQuests[!is.na(time) & !is.na(distance)]
```

Plotting average trial and learning times
```{r}
pltTab = tab[,list(mean=mean(time), sd = sd(time), se=sd(time)/sqrt(.N)), by=list(type)]
CompareMeansPlot(pltTab, 'type')
pairwise.t.test(tab$time,tab$type)
```

Plotting average trial and learning distances
```{r}
pltTab = tab[,list(mean=mean(distance), sd = sd(distance), se=sd(distance)/sqrt(.N)), by=list(type)] 
CompareMeansPlot(pltTab,'type')
pairwise.t.test(tab$distance,tab$type)
```


```{r, include = F}
tabEye = tab[type == "trial",list(meanDistance=mean(distance), sdDistance = sd(distance), seDistance=sd(distance)/sqrt(.N), meanTime=mean(time), sdTime = sd(time), seTime=sd(time)/sqrt(.N)), by=list(participant_id)]

tabMRI = tabM[type=="trial",list(meanDistance=mean(distance), sdDistance = sd(distance), seDistance=sd(distance)/sqrt(.N), meanTime=mean(time), sdTime = sd(time), seTime=sd(time)/sqrt(.N),nFinished = sum(finished), meanDistanceToEnd = mean(trailDistanceToEnd), closeToEnd = sum(trailDistanceToEnd < 100)), by=participant_id]

tabComplete = merge(tabEye, tabMRI, by='participant_id')
```

Plotting average time in trials in Eyetracker vs number of finished trials in MRI
```{r}
pltTab = tabComplete[,list(mean = mean(meanTime.x), sd = sd(meanTime.x), se=sd(meanTime.x)/sqrt(.N)), by = list(nFinished)]
CompareMeansPlot(pltTab,'nFinished')
```

Plotting average distance in trials in Eyetracker vs number of finished trials in MRI
```{r}
pltTab = tabComplete[,list(mean = mean(meanDistance.x), sd = sd(meanDistance.x), se=sd(meanDistance.x)/sqrt(.N)), by = list(nFinished)]
CompareMeansPlot(pltTab,'nFinished')
```