#libraries in correct order
library('R6')
library('data.table')
library('plyr')
library('dplyr')
library('stringr')
library('png')
library('grid')
library('ggplot2')
library('ggthemr')
library('ggthemes')
#custom items

dir = getwd()
source(paste(dir, "R/HelperFunctions/helper_functions.R", sep = "/"))
source_folder(paste(dir,"R/HelperFunctions/", sep = "/"))
source_folder(paste(dir,"R/AnalysisFunctions/", sep = "/"))
source_folder(paste(dir,"R/Classes/", sep = "/"))
source_folder(paste(dir,"R/Preprocessing/", sep = "/"))
source_folder(paste(dir,"R/Preprocessing/Importing", sep = "/"))
source_folder(paste(dir,"R/Preprocessing/Helpers/", sep = "/"))
source_folder(paste(dir,"R/Eyetracker/", sep = "/"))
source_folder(paste(dir,"R/Reporting/", sep = "/"))
source_folder(paste(dir,"R/DataManipulations/", sep = "/"))
source_folder(paste(dir,"R/Graphing/", sep = "/"))
source_folder(paste(dir,"R/MRI/", sep = "/"))
source_folder(paste(dir,"R/Unity/", sep = "/"))
